name: Metrics
on:
  schedule: [{cron: "0 */2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          user: lorencerri
          use_prebuilt_image: yes
          template: classic
          config_timezone: America/New_York
          plugin_lines: yes
          plugin_stargazers: yes
          config_padding: 16, 48
          # base
          base: header, activity, community, repositories, metadata
          repositories_forks: no
          # languages
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          # habits
          plugin_habits: yes
          plugin_habits_from: 1000       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          # reactions
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot]
          plugin_reactions_limit: 200
          # followup
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          # achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
